#!/bin/sh

banner() {
cat <<'eof'
   __             __  ___                  _
  / _|_      __   \ \/ / |_ _ __ __ _  ___| |_ ___  _ __
 | |_\ \ /\ / /____\  /| __| '__/ _` |/ __| __/ _ \| '__|
 |  _|\ V  V /_____/  \| |_| | | (_| | (__| || (_) | |
 |_|   \_/\_/     /_/\_\\__|_|  \__,_|\___|\__\___/|_|
         by @shubhamvis98 | https://fossfrog.in

eof
}

banner

FILE=$1
OUTPUT=$(pwd)/output
export PATH=$PATH:$(pwd)/bin

if [ ! -f "${FILE}" ]; then
	echo "[!]Input file doesn't exist"
	exit
else
	mkdir -p ${OUTPUT}
fi

chdir() {
	cd $1
}

rootdir() {
	cd $OUTPUT
}

sed 's|\(destination *= *"[^"]*"\),|\n{ \1 },\n|;s|^[[:space:]]*||' ${FILE} \
	| awk -F'"' '/name/ { print $2 } /destination/ { if ($2 != "") { print "chdir " $2 } else { print "chdir ROOTDIR" } }' \
	| while read line; do
		case $line in
			chdir*)
				if echo $line | grep -q ROOTDIR; then
					rootdir
				else
					rootdir
					mkdir -p $(echo $line | sed 's|chdir||')
					eval $line
				fi
				;;
			*)
				find /vendor -name $line | tee ${line}_res | while read FW; do
					BNAME=$(basename $line)
					NEXT=$(echo $BNAME | cut -d. -f1)
					case $line in
						*.mdt)
							echo "[+]Squashing ${BNAME}"
							pil-squasher ${NEXT}.mbn ${FW}
							;;
						*)
							echo "[+]Copying ${BNAME}"
							cp ${FW} .
							;;
					esac
				done
				if [ ! -s "${line}_res" ]; then
					echo "[!]${line} doesn't exist"
				fi
				rm "${line}_res"
				;;	
		esac
	done
