#!/bin/sh
# -------------------------------------------------------------------------------
#  Script Name : fw-Xtractor
#  Author      : Shubham Vishwakarma [@shubhamvis98]
#  Web         : https://fossfrog.in
#
#  MIT License
#  Copyright (c) 2024 Shubham Vishwakarma
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
# -------------------------------------------------------------------------------

banner() {
cat <<'eof'
   __             __  ___                  _
  / _|_      __   \ \/ / |_ _ __ __ _  ___| |_ ___  _ __
 | |_\ \ /\ / /____\  /| __| '__/ _` |/ __| __/ _ \| '__|
 |  _|\ V  V /_____/  \| |_| | | (_| | (__| || (_) | |
 |_|   \_/\_/     /_/\_\\__|_|  \__,_|\___|\__\___/|_|
         by @shubhamvis98 | https://fossfrog.in

eof
}

banner

FILE=$1
OUTPUT=$(pwd)/output
export PATH=$PATH:$(pwd)/bin

if [ ! -f "${FILE}" ]; then
	echo "[!]Input file doesn't exist"
	exit
else
	mkdir -p ${OUTPUT}
fi

chdir() {
	cd $1
}

rootdir() {
	cd $OUTPUT
}

sed 's|\(destination *= *"[^"]*"\),|\n{ \1 },\n|;s|^[[:space:]]*||' ${FILE} \
	| awk -F'"' '/name/ { print $2 } /destination/ { if ($2 != "") { print "chdir " $2 } else { print "chdir ROOTDIR" } }' \
	| while read line; do
		case $line in
			chdir*)
				if echo $line | grep -q ROOTDIR; then
					rootdir
				else
					rootdir
					mkdir -p $(echo $line | sed 's|chdir||')
					eval $line
				fi
				;;
			*)
				find /vendor -name $line | tee ${line}_res | while read FW; do
					BNAME=$(basename $line)
					NEXT=$(echo $BNAME | cut -d. -f1)
					case $line in
						*.mdt)
							echo "[+]Squashing ${BNAME}"
							pil-squasher ${NEXT}.mbn ${FW}
							;;
						*)
							echo "[+]Copying ${BNAME}"
							cp ${FW} .
							;;
					esac
				done
				if [ ! -s "${line}_res" ]; then
					echo "[!]${line} doesn't exist"
				fi
				rm "${line}_res"
				;;	
		esac
	done
